# Generated by Django 4.2.6 on 2023-10-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livromodel',
            name='autor',
            field=models.CharField(default='Autor Desconhecido', max_length=200, verbose_name='Autor'),
        ),
    ]
