# Generated by Django 4.2.6 on 2023-10-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_livromodel_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livromodel',
            name='autor',
            field=models.CharField(max_length=200, verbose_name='Autor'),
        ),
    ]
