# Generated by Django 4.2.6 on 2023-10-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_livromodel_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='livromodel',
            name='ano',
            field=models.IntegerField(default=0, verbose_name='Ano de Publicação'),
            preserve_default=False,
        ),
    ]
