# Generated by Django 4.2.6 on 2023-10-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_livromodel_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livromodel',
            name='ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de Publicação'),
        ),
    ]
