# Generated by Django 4.2.6 on 2023-10-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_livromodel_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livromodel',
            name='ano',
            field=models.IntegerField(verbose_name='Ano de Publicação'),
        ),
    ]
