# Generated by Django 4.2.6 on 2023-10-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_livromodel_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livromodel',
            name='ano',
            field=models.CharField(max_length=4, verbose_name='Ano de Publicação'),
        ),
    ]
