# Generated by Django 4.2.6 on 2023-10-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_livromodel_nundepaginas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livromodel',
            old_name='nunDePaginas',
            new_name='numDePaginas',
        ),
    ]
