# Generated by Django 4.2.6 on 2023-11-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_nundepaginas_livromodel_numdepaginas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livromodel',
            name='numDePaginas',
        ),
        migrations.AddField(
            model_name='livromodel',
            name='paginas',
            field=models.CharField(default=123, max_length=4, verbose_name='Número de páginas do livro'),
            preserve_default=False,
        ),
    ]
